# **Automatidata project**
**Course 1 - Foundations of Data Science**

Welcome to the Automatidata Project!

You have just started as a data professional in a fictional data consulting firm, Automatidata. Their client, the New York City Taxi and Limousine Commission (New York City TLC), has hired the Automatidata team for its reputation in helping their clients develop data-based solutions.

The team is still in the early stages of the project. You have received notice that New York City TLC has given the Automatidata team access to their data. To get clear insights, New York TLC's data must be inspected, key variables identified, and the dataset prepared for analysis.

A notebook was structured and prepared to help you in this project. Please complete the following questions.

# Course 1 End-of-course project: Inspect and analyze data

In this activity, you will examine data provided and prepare it for analysis.  This activity will help ensure the information is,

1.   Ready to answer questions and yield insights

2.   Ready for visualizations

3.   Ready for future hypothesis testing and statistical methods
<br/>    

**The purpose** of this project is to investigate and understand the data provided.
  
**The goal** is to use a dataframe contructed within Python, perform a cursory inspection of the provided dataset, and inform team members of your findings. 
<br/>  
*This activity has three parts:*

**Part 1:** Understand the situation 
* Prepare to understand and organize the provided taxi cab dataset and information.

**Part 2:** Understand the data

* Create a pandas dataframe for data learning, future exploratory data analysis (EDA), and statistical activities.

* Compile summary information about the data to inform next steps.

**Part 3:** Understand the variables

* Use insights from your examination of the summary data to guide deeper investigation into specific variables.


<br/> 
Follow the instructions and answer the following questions to complete the activity. Then, you will complete an Executive Summary using the questions listed on the PACE Strategy Document.

Be sure to complete this activity before moving on. The next course item will provide you with a completed exemplar to compare to your own work.

# **Identify data types and relevant variables using Python**



# **PACE stages**

Throughout these project notebooks, you'll see references to the problem-solving framework PACE. The following notebook components are labeled with the respective PACE stage: Plan, Analyze, Construct, and Execute.




## PACE: **Plan**

Consider the questions in your PACE Strategy Document and those below to craft your response:

### **Task 1. Understand the situation**

*   How can you best prepare to understand and organize the provided taxi cab information?

Review the project instructions, understand the business objective, examine the data dictionary if available, inspect the dataset structure, and organize the files before beginning the analysis. This helps ensure the data is interpreted correctly and the workflow remains organized.



## PACE: **Analyze**

Consider the questions in your PACE Strategy Document to reflect on the Analyze stage.

### **Task 2a. Build dataframe**

Create a pandas dataframe for data learning, and future exploratory data analysis (EDA) and statistical activities.

**Code the following,**

*   import pandas as `pd`. pandas is used for buidling dataframes.

*   import numpy as `np`. numpy is imported with pandas

*   `df = pd.read_csv('Datasets\NYC taxi data.csv')`

**Note:** pair the data object name `df` with pandas functions to manipulate data, such as `df.groupby()`.

**Note:** As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [1]:
#Import libraries and packages listed above
import pandas as pd
import numpy as np

# Load dataset into dataframe
df = pd.read_csv('2017_Yellow_Taxi_Trip_Data.csv')
print("done")

done

### **Task 2b. Understand the data - Inspect the data**

View and inspect summary information about the dataframe by coding the following:

1. `df.head(10)`
2. `df.info()`
3. `df.describe()`

Consider the following two questions:

**Question 1:** When reviewing the `df.info()` output, what do you notice about the different variables? Are there any null values? Are all of the variables numeric? Does anything else stand out?

**Question 2:** When reviewing the `df.describe()` output, what do you notice about the distributions of each variable? Are there any questionable values?

The dataset contains 22,699 rows and 18 columns. There are no missing values, as every column contains 22,699 non-null entries. The dataset includes integer, float, and string variables, so not all variables are numeric. The pickup and dropoff datetime columns are stored as strings and should be converted to datetime format if time-based analysis is needed. Additionally, the Unnamed: 0 column appears to be an automatically generated index rather than a meaningful data variable and may not be necessary for analysis.

The descriptive statistics show that most variables have reasonable distributions; however, there are several anomalies and outliers in the dataset. For example, the trip_distance variable has a maximum value of 33.96, which is significantly higher than the upper quartile (3.06), indicating potential long-distance outliers. The fare_amount variable also shows unusual values, including a minimum of -120.00 and a maximum of 999.99, which are not realistic for taxi fares. Similarly, total_amount includes negative values such as -120.30, which suggests possible data entry errors or refunds. Additionally, tip_amount has a maximum value of 200, which is unusually high compared to the median. These observations indicate the presence of outliers and potentially incorrect records that should be further investigated or cleaned before analysis.

In [2]:
df.head(10)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80
5,23345809,2,03/25/2017 8:34:11 PM,03/25/2017 8:42:11 PM,6,2.30,1,N,161,236,1,9.0,0.5,0.5,2.06,0.0,0.3,12.36
6,37660487,2,05/03/2017 7:04:09 PM,05/03/2017 8:03:47 PM,1,12.83,1,N,79,241,1,47.5,1.0,0.5,9.86,0.0,0.3,59.16
7,69059411,2,08/15/2017 5:41:06 PM,08/15/2017 6:03:05 PM,1,2.98,1,N,237,114,1,16.0,1.0,0.5,1.78,0.0,0.3,19.58
8,8433159,2,02/04/2017 4:17:07 PM,02/04/2017 4:29:14 PM,1,1.20,1,N,234,249,2,9.0,0.0,0.5,0.00,0.0,0.3,9.80
9,95294817,1,11/10/2017 3:20:29 PM,11/10/2017 3:40:55 PM,1,1.60,1,N,239,237,1,13.0,0.0,0.5,2.75,0.0,0.3,16.55

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22699 entries, 0 to 22698
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             22699 non-null  int64
 1   VendorID               22699 non-null  int64
 2   tpep_pickup_datetime   22699 non-null  str
 3   tpep_dropoff_datetime  22699 non-null  str
 4   passenger_count        22699 non-null  int64
 5   trip_distance          22699 non-null  float64
 6   RatecodeID             22699 non-null  int64
 7   store_and_fwd_flag     22699 non-null  str
 8   PULocationID           22699 non-null  int64
 9   DOLocationID           22699 non-null  int64
 10  payment_type           22699 non-null  int64
 11  fare_amount            22699 non-null  float64
 12  extra                  22699 non-null  float64
 13  mta_tax                22699 non-null  float64
 14  tip_amount             22699 non-null  float64
 15  tolls_amount           22699 non-null  float64
 16  improvement_surcharge  22699 non-null  float64
 17  total_amount           22699 non-null  float64
dtypes: float64(8), int64(7), str(3)
memory usage: 3.1 MB

In [4]:
df.describe()

,Unnamed: 0,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,2.269900e+04,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000
mean,5.675849e+07,1.556236,1.642319,2.913313,1.043394,162.412353,161.527997,1.336887,13.026629,0.333275,0.497445,1.835781,0.312542,0.299551,16.310502
std,3.274493e+07,0.496838,1.285231,3.653171,0.708391,66.633373,70.139691,0.496211,13.243791,0.463097,0.039465,2.800626,1.399212,0.015673,16.097295
min,1.212700e+04,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,2.852056e+07,1.000000,1.000000,0.990000,1.000000,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,5.673150e+07,2.000000,1.000000,1.610000,1.000000,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,8.537452e+07,2.000000,2.000000,3.060000,1.000000,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,1.134863e+08,2.000000,6.000000,33.960000,99.000000,265.000000,265.000000,4.000000,999.990000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

### **Task 2c. Understand the data - Investigate the variables**

Sort and interpret the data table for two variables:`trip_distance` and `total_amount`.

**Answer the following three questions:**

**Question 1:** Sort your first variable (`trip_distance`) from maximum to minimum value, do the values seem normal?

**Question 2:** Sort by your second variable (`total_amount`), are any values unusual?

**Question 3:** Are the resulting rows similar for both sorts? Why or why not?

1. After sorting trip_distance in descending order, we observe multiple unusually high values, not just a single outlier. Several trips range between approximately 27 km and 34 km, which is significantly higher than the typical distribution of the dataset, where most trips are below 3 km. While long-distance trips can occur in taxi services, the frequency and magnitude of these values suggest the presence of potential outliers or special trip types that should be further investigated before further analysis.

2. After sorting total_amount in both descending and ascending order, multiple anomalies are observed. On the upper end, there are extreme outliers such as 1200.29 and other values above 200, which are far beyond the typical range of taxi fares. On the lower end, there are several negative values, including -120.30 and other negative totals. These values are not realistic for standard taxi trips and may represent refunds, data entry errors, or special adjustment cases. Overall, the distribution shows significant inconsistencies, indicating that data cleaning or filtering of outliers is necessary before further analysis.

3. The dataset shows that payment type 1 (credit card) is the most common method with 15,265 trips, followed by payment type 2 (cash) with 7,267 trips.
Payment types 3 (no charge) and 4 (dispute) appear very rarely, with 121 and 46 occurrences respectively.
This indicates that the vast majority of trips are paid either by credit card or cash, with credit card being the dominant payment method.
The presence of payment types 3 and 4 suggests edge cases such as waived fares or disputes, which may introduce noise into financial analysis and should be handled carefully in modeling.

In [5]:
df.sort_values(by='trip_distance', ascending=False).head(10)

# Sort the data by trip distance from maximum to minimum value

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
9280,51810714,2,06/18/2017 11:33:25 PM,06/19/2017 12:12:38 AM,2,33.96,5,N,132,265,2,150.00,0.0,0.0,0.00,0.00,0.3,150.30
13861,40523668,2,05/19/2017 8:20:21 AM,05/19/2017 9:20:30 AM,1,33.92,5,N,229,265,1,200.01,0.0,0.5,51.64,5.76,0.3,258.21
6064,49894023,2,06/13/2017 12:30:22 PM,06/13/2017 1:37:51 PM,1,32.72,3,N,138,1,1,107.00,0.0,0.0,55.50,16.26,0.3,179.06
10291,76319330,2,09/11/2017 11:41:04 AM,09/11/2017 12:18:58 PM,1,31.95,4,N,138,265,2,131.00,0.0,0.5,0.00,0.00,0.3,131.80
29,94052446,2,11/06/2017 8:30:50 PM,11/07/2017 12:00:00 AM,1,30.83,1,N,132,23,1,80.00,0.5,0.5,18.56,11.52,0.3,111.38
18130,90375786,1,10/26/2017 2:45:01 PM,10/26/2017 4:12:49 PM,1,30.50,1,N,132,220,1,90.50,0.0,0.5,19.85,8.16,0.3,119.31
5792,68023798,2,08/11/2017 2:14:01 PM,08/11/2017 3:17:31 PM,1,30.33,2,N,132,158,1,52.00,0.0,0.5,14.64,5.76,0.3,73.20
15350,77309977,2,09/14/2017 1:44:44 PM,09/14/2017 2:34:29 PM,1,28.23,2,N,13,132,1,52.00,0.0,0.5,4.40,5.76,0.3,62.96
10302,43431843,1,05/15/2017 8:11:34 AM,05/15/2017 9:03:16 AM,1,28.20,2,N,90,132,1,52.00,0.0,0.5,11.71,5.76,0.3,70.27
2592,51094874,2,06/16/2017 6:51:20 PM,06/16/2017 7:41:42 PM,1,27.97,2,N,261,132,2,52.00,4.5,0.5,0.00,5.76,0.3,63.06

In [6]:
df.sort_values(by='total_amount', ascending=False).head(20)

# Sort the data by total amount and print the top 20 values

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
8476,11157412,1,02/06/2017 5:50:10 AM,02/06/2017 5:51:08 AM,1,2.60,5,N,226,226,1,999.99,0.0,0.0,200.00,0.00,0.3,1200.29
20312,107558404,2,12/19/2017 9:40:46 AM,12/19/2017 9:40:55 AM,2,0.00,5,N,265,265,2,450.00,0.0,0.0,0.00,0.00,0.3,450.30
13861,40523668,2,05/19/2017 8:20:21 AM,05/19/2017 9:20:30 AM,1,33.92,5,N,229,265,1,200.01,0.0,0.5,51.64,5.76,0.3,258.21
12511,107108848,2,12/17/2017 6:24:24 PM,12/17/2017 6:24:42 PM,1,0.00,5,N,265,265,1,175.00,0.0,0.0,46.69,11.75,0.3,233.74
15474,55538852,2,06/06/2017 8:55:01 PM,06/06/2017 8:55:06 PM,1,0.00,5,N,265,265,1,200.00,0.0,0.5,11.00,0.00,0.3,211.80
6064,49894023,2,06/13/2017 12:30:22 PM,06/13/2017 1:37:51 PM,1,32.72,3,N,138,1,1,107.00,0.0,0.0,55.50,16.26,0.3,179.06
16379,101198443,2,11/30/2017 10:41:11 AM,11/30/2017 11:31:45 AM,1,25.50,5,N,132,265,2,140.00,0.0,0.5,0.00,16.26,0.3,157.06
3582,111653084,1,01/01/2017 11:53:01 PM,01/01/2017 11:53:42 PM,1,7.30,5,N,1,1,1,152.00,0.0,0.0,0.00,0.00,0.3,152.30
11269,51920669,1,06/19/2017 12:51:17 AM,06/19/2017 12:52:12 AM,2,0.00,5,N,265,265,1,120.00,0.0,0.0,20.00,11.52,0.3,151.82
9280,51810714,2,06/18/2017 11:33:25 PM,06/19/2017 12:12:38 AM,2,33.96,5,N,132,265,2,150.00,0.0,0.0,0.00,0.00,0.3,150.30
1928,51087145,1,06/16/2017 6:30:08 PM,06/16/2017 7:18:50 PM,2,12.50,5,N,211,265,1,120.00,0.0,0.0,5.00,12.50,0.3,137.80
10291,76319330,2,09/11/2017 11:41:04 AM,09/11/2017 12:18:58 PM,1,31.95,4,N,138,265,2,131.00,0.0,0.5,0.00,0.00,0.3,131.80
6708,91660295,2,10/30/2017 11:23:46 AM,10/30/2017 11:23:49 AM,1,0.32,5,N,264,83,1,100.00,0.0,0.5,25.20,0.00,0.3,126.00
11608,107690629,2,12/19/2017 5:00:56 PM,12/19/2017 6:41:56 PM,2,23.00,3,N,151,1,1,99.50,1.0,0.0,10.00,12.50,0.3,123.30
908,25075013,2,03/27/2017 1:01:38 PM,03/27/2017 1:38:44 PM,2,26.12,4,N,138,265,1,100.00,0.0,0.5,15.00,5.76,0.3,121.56
7281,111091850,2,01/01/2017 3:02:53 AM,01/01/2017 3:03:02 AM,1,0.00,5,N,265,265,1,100.00,0.0,0.5,20.16,0.00,0.3,120.96
18130,90375786,1,10/26/2017 2:45:01 PM,10/26/2017 4:12:49 PM,1,30.50,1,N,132,220,1,90.50,0.0,0.5,19.85,8.16,0.3,119.31
13621,93330154,1,11/04/2017 1:32:14 PM,11/04/2017 2:18:50 PM,2,19.80,5,N,265,230,1,105.00,0.0,0.0,8.00,2.64,0.3,115.94
13359,3055315,1,01/12/2017 7:19:36 AM,01/12/2017 7:19:56 AM,1,0.00,5,N,1,1,1,75.00,0.0,0.0,18.65,18.00,0.3,111.95
29,94052446,2,11/06/2017 8:30:50 PM,11/07/2017 12:00:00 AM,1,30.83,1,N,132,23,1,80.00,0.5,0.5,18.56,11.52,0.3,111.38

In [7]:
df.sort_values(by='total_amount', ascending=True).head(20)

# Sort the data by total amount and print the bottom 20 values

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
12944,29059760,2,04/08/2017 12:00:16 AM,04/08/2017 11:15:57 PM,1,0.17,5,N,138,138,4,-120.00,0.0,0.0,0.0,0.0,-0.3,-120.30
17602,24690146,2,03/24/2017 7:31:13 PM,03/24/2017 7:34:49 PM,1,0.46,1,N,87,45,4,-4.00,-1.0,-0.5,0.0,0.0,-0.3,-5.80
20698,14668209,2,02/24/2017 12:38:17 AM,02/24/2017 12:42:05 AM,1,0.70,1,N,65,25,4,-4.50,-0.5,-0.5,0.0,0.0,-0.3,-5.80
11204,58395501,2,07/09/2017 7:20:59 AM,07/09/2017 7:23:50 AM,1,0.64,1,N,50,48,3,-4.50,0.0,-0.5,0.0,0.0,-0.3,-5.30
14714,109276092,2,12/24/2017 10:37:58 PM,12/24/2017 10:41:08 PM,5,0.40,1,N,164,161,4,-4.00,-0.5,-0.5,0.0,0.0,-0.3,-5.30
20317,75926915,2,09/09/2017 10:59:51 PM,09/09/2017 11:02:06 PM,1,0.24,1,N,116,116,4,-3.50,-0.5,-0.5,0.0,0.0,-0.3,-4.80
8204,91187947,2,10/28/2017 8:39:36 PM,10/28/2017 8:41:59 PM,1,0.41,1,N,236,237,3,-3.50,-0.5,-0.5,0.0,0.0,-0.3,-4.80
4423,97329905,2,11/16/2017 8:13:30 PM,11/16/2017 8:14:50 PM,2,0.06,1,N,237,237,4,-3.00,-0.5,-0.5,0.0,0.0,-0.3,-4.30
10281,55302347,2,06/05/2017 5:34:25 PM,06/05/2017 5:36:29 PM,2,0.00,1,N,238,238,4,-2.50,-1.0,-0.5,0.0,0.0,-0.3,-4.30
5448,28459983,2,04/06/2017 12:50:26 PM,04/06/2017 12:52:39 PM,1,0.25,1,N,90,68,3,-3.50,0.0,-0.5,0.0,0.0,-0.3,-4.30
18565,43859760,2,05/22/2017 3:51:20 PM,05/22/2017 3:52:22 PM,1,0.10,1,N,230,163,3,-3.00,0.0,-0.5,0.0,0.0,-0.3,-3.80
5758,833948,2,01/03/2017 8:15:23 PM,01/03/2017 8:15:39 PM,1,0.02,1,N,170,170,3,-2.50,-0.5,-0.5,0.0,0.0,-0.3,-3.80
314,105454287,2,12/13/2017 2:02:39 AM,12/13/2017 2:03:08 AM,6,0.12,1,N,161,161,3,-2.50,-0.5,-0.5,0.0,0.0,-0.3,-3.80
1646,57337183,2,07/05/2017 11:02:23 AM,07/05/2017 11:03:00 AM,1,0.04,1,N,79,79,3,-2.50,0.0,-0.5,0.0,0.0,-0.3,-3.30
4402,108016954,2,12/20/2017 4:06:53 PM,12/20/2017 4:47:50 PM,1,7.06,1,N,263,169,2,0.00,0.0,0.0,0.0,0.0,0.0,0.00
5722,49670364,2,06/12/2017 12:08:55 PM,06/12/2017 12:08:57 PM,1,0.00,1,N,264,193,1,0.00,0.0,0.0,0.0,0.0,0.0,0.00
22566,19022898,2,03/07/2017 2:24:47 AM,03/07/2017 2:24:50 AM,1,0.00,1,N,264,193,1,0.00,0.0,0.0,0.0,0.0,0.0,0.00
10506,26005024,2,03/30/2017 3:14:26 AM,03/30/2017 3:14:28 AM,1,0.00,1,N,264,193,1,0.00,0.0,0.0,0.0,0.0,0.0,0.00
19067,58713019,1,07/10/2017 2:40:09 PM,07/10/2017 2:40:59 PM,1,0.10,5,N,261,13,3,0.00,0.0,0.0,0.0,0.0,0.3,0.30
14283,37675840,1,05/03/2017 7:44:28 PM,05/03/2017 7:44:38 PM,1,0.00,5,N,146,146,3,0.01,0.0,0.0,0.0,0.0,0.3,0.31

In [10]:
df['payment_type'].value_counts()

# How many of each payment type are represented in the data?

payment_type
1    15265
2     7267
3      121
4       46
Name: count, dtype: int64

According to the data dictionary, the payment method was encoded as follows:

1 = Credit card  
2 = Cash  
3 = No charge  
4 = Dispute  
5 = Unknown  
6 = Voided trip

In [15]:
Card_Average =df[df['payment_type']== 1]['tip_amount'].mean()

# What is the average tip for trips paid for with credit card?

Cash_Average = df[df['payment_type']== 2]['tip_amount'].mean()

# What is the average tip for trips paid for with cash?

print(Card_Average, Cash_Average)

2.7298001965280054 0.0

In [17]:
df['VendorID'].value_counts()

# How many times is each vendor ID represented in the data?

VendorID
2    12626
1    10073
Name: count, dtype: int64

In [18]:
df.groupby('VendorID')['total_amount'].mean()

# What is the mean total amount for each vendor?

VendorID
1    16.298119
2    16.320382
Name: total_amount, dtype: float64

In [21]:
credit_card = df[df['payment_type'] == 1]

# Filter the data for credit card payments only

credit_card_passenger = credit_card[['passenger_count', 'tip_amount']]

# Filter the credit-card-only data for passenger count only
print(credit_card_passenger.head(10))

    passenger_count  tip_amount
0                 6        2.76
1                 1        4.00
2                 1        1.45
3                 1        6.39
5                 6        2.06
6                 1        9.86
7                 1        1.78
9                 1        2.75
10                1        2.46
11                2       14.58

In [22]:
credit_card.groupby('passenger_count')['tip_amount'].mean()

# Calculate the average tip amount for each passenger count (credit card payments only)

passenger_count
0    2.610370
1    2.714681
2    2.829949
3    2.726800
4    2.607753
5    2.762645
6    2.643326
Name: tip_amount, dtype: float64



## PACE: **Construct**

**Note**: The Construct stage does not apply to this workflow. The PACE framework can be adapted to fit the specific requirements of any project.