# Activity: Validate and clean your data

## Introduction

In this activity, you will use input validation and label encoding to prepare a dataset for analysis. These are fundamental techniques used in all types of data analysis, from simple linear regression to complex neural networks. 

In this activity, you are a data professional an investment firm that is attempting to invest in private companies with a valuation of at least $1 billion. These are often known as "unicorns." Your client wants to develop a better understanding of unicorns, with the hope they can be early investors in future highly successful companies. They are particularly interested in the investment strategies of the three top unicorn investors: Sequoia Capital, Tiger Global Management, and Accel.

## Step 1: Imports

Import relevant Python libraries and packages: `numpy`, `pandas`, `seaborn`, and `pyplot` from `matplotlib`.

In [1]:
# Import libraries and packages.

import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

### Load the dataset

The data contains details about unicorn companies, such as when they were founded, when they achieved unicorn status, and their current valuation. The dataset `Modified_Unicorn_Companies.csv` is loaded as `companies`, now display the first five rows. The variables in the dataset have been adjusted to suit the objectives of this lab, so they may be different from similar data used in prior labs. As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [2]:
# Run this cell so pandas displays all columns
pd.set_option('display.max_columns', None)

In [3]:
# RUN THIS CELL TO IMPORT YOUR DATA. 
companies = pd.read_csv('Modified_Unicorn_Companies.csv')

# Display the first five rows.
companies.head(5)

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."

## Step 2: Data cleaning

Begin by displaying the data types of the columns in `companies`.

In [4]:
# Display the data types of the columns.

companies.dtypes

Company               str
Valuation           int64
Date Joined           str
Industry              str
City                  str
Country/Region        str
Continent             str
Year Founded        int64
Funding               str
Select Investors      str
dtype: object

### Modify the data types

Notice that the data type of the `Date Joined` column is an `object`&mdash;in this case, a string. Convert this column to `datetime` to make it more usable.

In [5]:
# Apply necessary datatype conversions.

companies['Date Joined'] = pd.to_datetime(companies['Date Joined'])
companies.dtypes

Company                        str
Valuation                    int64
Date Joined         datetime64[us]
Industry                       str
City                           str
Country/Region                 str
Continent                      str
Year Founded                 int64
Funding                        str
Select Investors               str
dtype: object

### Create a new column

Add a column called `Years To Unicorn`, which is the number of years between when the company was founded and when it became a unicorn.

In [6]:
# Create the column Years To Unicorn.

companies['Years to Unicorn'] = pd.to_datetime(companies['Date Joined']).dt.year - companies['Year Founded']
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",5
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",10
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",10
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",4
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",6

**QUESTION: Why might your client be interested in how quickly a company achieved unicorn status?**

A client might be interested in how quickly a company achieved unicorn status because it indicates the company's growth rate and potential. Companies that reach a valuation of $1 billion in a shorter time may have stronger business performance, higher investor confidence, or operate in rapidly growing industries. This information can help identify trends and support investment or business decisions.

### Input validation

The data has some issues with bad data, duplicate rows, and inconsistent `Industry` labels.

Identify and correct each of these issues.

#### Correcting bad data

Get descriptive statistics for the `Years To Unicorn` column.

In [7]:
# Identify and correct the issue with Years To Unicorn.

companies.describe()

         Valuation                 Date Joined  Year Founded  Years to Unicorn
count  1074.000000                        1074   1074.000000       1074.000000
mean      3.445996  2020-05-14 20:22:47.597765   2012.870577          7.013035
min       1.000000         2007-07-02 00:00:00   1919.000000         -3.000000
25%       1.000000         2019-05-15 06:00:00   2011.000000          4.000000
50%       2.000000         2021-03-26 00:00:00   2014.000000          6.000000
75%       3.000000         2021-09-16 00:00:00   2016.000000          9.000000
max     180.000000         2022-04-05 00:00:00   2021.000000         98.000000
std       8.544242                         NaN      5.705494          5.331842

Isolate all rows where the `Years To Unicorn` column contains a negative value.

In [8]:
# Isolate any rows where `Years To Unicorn` is negative

companies[companies['Years to Unicorn'] <= 0]

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn
160,Ola Electric Mobility,5,2019-07-02,Auto & transportation,Bengaluru,India,Asia,2019,$761M,"SoftBank Group, Tiger Global Management, Matri...",0
313,Flink Food,3,2021-12-01,E-commerce & direct-to-consumer,Berlin,Germany,Europe,2021,$1B,"Mubadala Capital, Bond, Prosus Ventures",0
396,candy.com,2,2021-10-21,Fintech,New York,United States,North America,2021,$100M,"Insight Partners, Softbank Group, Connect Vent...",0
527,InVision,2,2017-11-01,Internet software & services,New York,United States,North America,2020,$349M,"FirstMark Capital, Tiger Global Management, IC...",-3
545,Avant,2,2012-12-17,Artificial intelligence,Chicago,United States,North America,2012,$658M,"RRE Ventures, Tiger Global, August Capital",0
553,ClickHouse,2,2021-10-28,Data management & analytics,Portola Valley,United States,North America,2021,$300M,"Lightspeed Venture Partners, Almaz Capital Par...",0
774,Jokr,1,2021-12-02,E-commerce & direct-to-consumer,New York,United States,North America,2021,$430M,"GGV Capital, Tiger Global Management, Greycroft",0
821,GlobalBees,1,2021-12-28,E-commerce & direct-to-consumer,New Delhi,India,Asia,2021,$185M,"Chiratae Ventures, SoftBank Group, Trifecta Ca...",0
966,Mensa Brands,1,2021-11-16,Other,Bengaluru,India,Asia,2021,$218M,"Accel, Falcon Edge Capital, Norwest Venture Pa...",0
1000,Playco,1,2020-09-21,Other,Tokyo,Japan,Asia,2020,$140M,"Sozo Ventures, Caffeinated Capital, Sequoia Ca...",0

**Question: How many rows have negative values in the `Years To Unicorn` column, and what companies are they for?**

The company InVision has negative value in the Years to Unicorn column, has -3.

An internet search reveals that InVision was founded in 2011. Replace the value at `Year Founded` with `2011` for InVision's row.

In [9]:
# Replace InVision's `Year Founded` value with 2011

companies.loc[companies['Company']== 'InVision', 'Year Founded'] = 2011

# Verify the change was made properly

companies.loc[companies['Company']== 'InVision']

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn
527,InVision,2,2017-11-01,Internet software & services,New York,United States,North America,2011,$349M,"FirstMark Capital, Tiger Global Management, IC...",-3

Now, recalculate all the values in the `Years To Unicorn` column to remove the negative value for InVision. Verify that there are no more negative values afterwards.

In [10]:
# Recalculate all values in the `Years To Unicorn` column

companies['Years to Unicorn'] = pd.to_datetime(companies['Date Joined']).dt.year - companies['Year Founded']

# Verify that there are no more negative values in the column

companies.describe()

         Valuation                 Date Joined  Year Founded  Years to Unicorn
count  1074.000000                        1074   1074.000000       1074.000000
mean      3.445996  2020-05-14 20:22:47.597765   2012.862197          7.021415
min       1.000000         2007-07-02 00:00:00   1919.000000          0.000000
25%       1.000000         2019-05-15 06:00:00   2011.000000          4.000000
50%       2.000000         2021-03-26 00:00:00   2014.000000          6.000000
75%       3.000000         2021-09-16 00:00:00   2016.000000          9.000000
max     180.000000         2022-04-05 00:00:00   2021.000000         98.000000
std       8.544242                         NaN      5.701621          5.323155

#### Issues with `Industry` labels

The company provided you with the following list of industry labels to identify in the data for `Industry`. 

**Note:** Any labels in the `Industry` column that are not in `industry_list` are misspellings.

In [11]:
# List provided by the company of the expected industry labels in the data
industry_list = ['Artificial intelligence', 'Other','E-commerce & direct-to-consumer', 'Fintech',\
       'Internet software & services','Supply chain, logistics, & delivery', 'Consumer & retail',\
       'Data management & analytics', 'Edtech', 'Health', 'Hardware','Auto & transportation', \
        'Travel', 'Cybersecurity','Mobile & telecommunications']

First, check if there are values in the `Industry` column that are not in `industry_list`. If so, what are they?

In [12]:
# Check which values are in `Industry` but not in `industry_list`

set(companies['Industry']) - set(industry_list)

{'Artificial Intelligence', 'Data management and analytics', 'FinTech'}

**Question: Which values currently exist in the `Industry` column that are not in `industry_list`?**

This are the values: {'Artificial Intelligence', 'Data management and analytics', 'FinTech'}

Now, correct the bad entries in the `Industry` column by replacing them with an approved string from `industry_list`. To do this, use the [`replace()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html) `Series` method on the `Industry` series. When you pass a dictionary to the method, it will replace the data in the series where that data matches the dictionary's keys. The values that get imputed are the values of the dictionary. If a value is not specified in the dictionary, the series' original value is retained.
</br></br>


```
Example:

 [IN]: column_a = pd.Series(['A', 'B', 'C', 'D'])
       column_a

[OUT]: 0    A
       1    B
       2    C
       3    D
       dtype: object

 [IN]: replacement_dict = {'A':'z', 'B':'y', 'C':'x'}
       column_a = column_a.replace(replacement_dict)
       column_a
       
[OUT]: 0    z
       1    y
       2    x
       3    D
       dtype: object

```

1. Create a dictionary called `replacement_dict` whose keys are the incorrect spellings in the `Industry` series and whose values are the correct spelling, as indicated in `industry_list`.

2. Call the `replace()` method on the `Industry` series and pass to it `replacement_dict` as its argument. Reassign the result back to the `Industry` column.

3. Verify that there are no longer any elements in `Industry` that are not in `industry_list`.

In [13]:
# 1. Create `replacement_dict`

replacement_dict = {
    'Artificial Intelligence': 'Artificial intelligence',
    'Data management and analytics': 'Data management & analytics',
    'FinTech':'Fintech'
}


# 2. Replace the incorrect values in the `Industry` column

companies['Industry'] = companies['Industry'].replace(replacement_dict)

# 3. Verify that there are no longer any elements in `Industry` that are not in `industry_list`

set(companies['Industry']) - set(industry_list)

set()

#### Handling duplicate rows

The business mentioned that no company should appear in the data more than once.

Verify that this is indeed the case, and if not, clean the data so each company appears only once.

Begin by checking which, if any, companies are duplicated. Filter the data to return all occurrences of those duplicated companies.

In [14]:
# Isolate rows of all companies that have duplicates

companies[companies.duplicated(subset='Company', keep=False)]

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn
385,BrewDog,2,2017-04-10,Consumer & retail,Aberdeen,United Kingdom,Europe,2007,$233M,"TSG Consumer Partners, Crowdcube",10
386,BrewDog,2,2017-04-10,Consumer & retail,Aberdeen,UnitedKingdom,Europe,2007,$233M,TSG Consumer Partners,10
510,ZocDoc,2,2015-08-20,Health,New York,United States,North America,2007,$374M,"Founders Fund, Khosla Ventures, Goldman Sachs",8
511,ZocDoc,2,2015-08-20,Health,NaN,United States,North America,2007,$374M,Founders Fund,8
1031,SoundHound,1,2018-05-03,Artificial intelligence,Santa Clara,United States,North America,2005,$215M,"Tencent Holdings, Walden Venture Capital, Glob...",13
1032,SoundHound,1,2018-05-03,Other,Santa Clara,United States,North America,2005,$215M,Tencent Holdings,13

**Question: Do these duplicated companies seem like legitimate data points, or are they problematic data?**

The duplicated companies are problematic data points because each company should only appear once in the dataset. Having duplicate entries could affect analysis by incorrectly counting companies, skewing statistics, and producing inaccurate insights.

Keep the first occurrence of each duplicate company and drop the subsequent rows that are copies.

In [15]:
# Drop rows of duplicate companies after their first occurrence

companies = companies.drop_duplicates(subset='Company')

companies[companies.duplicated(subset='Company', keep=False)]

Empty DataFrame
Columns: [Company, Valuation, Date Joined, Industry, City, Country/Region, Continent, Year Founded, Funding, Select Investors, Years to Unicorn]
Index: []

**Question: Why is it important to perform input validation?**

Input validation is important because it helps ensure that the data being entered is accurate, consistent, and reliable. Validating inputs prevents errors, incorrect values, and unexpected data from affecting analysis and leading to inaccurate conclusions.

**Question: What steps did you take to perform input validation for this dataset?**

To perform input validation for this dataset, I checked for incorrect values, missing data, and duplicate entries. I compared the values in categorical columns against approved lists, corrected invalid entries, and verified that the data followed the expected format and requirements.

### Convert numerical data to categorical data

Sometimes, you'll want to simplify a numeric column by converting it to a categorical column. To do this, one common approach is to break the range of possible values into a defined number of equally sized bins and assign each bin a name. In the next step, you'll practice this process.

#### Create a `High Valuation` column

The data in the `Valuation` column represents how much money (in billions, USD) each company is valued at. Use the `Valuation` column to create a new column called `High Valuation`. For each company, the value in this column should be `low` if the company is in the bottom 50% of company valuations and `high` if the company is in the top 50%.

In [16]:
# Create new `High Valuation` column
# Use qcut to divide Valuation into 'high' and 'low' Valuation groups

companies['High Valuation'] = pd.qcut(
    companies['Valuation'],
    2,
    labels=["low", "high"]
)

companies['High Valuation'].value_counts()

High Valuation
low     717
high    354
Name: count, dtype: int64

### Convert categorical data to numerical data

Three common methods for changing categorical data to numerical are:

1. Label encoding: order matters (ordinal numeric labels)
2. Label encoding: order doesn't matter (nominal numeric labels)
3. Dummy encoding: order doesn't matter (creation of binary columns for each possible category contained in the variable)

The decision on which method to use depends on the context and must be made on a case-to-case basis. However, a distinction is typically made between categorical variables with equal weight given to all possible categories vs. variables with a hierarchical structure of importance to their possible categories.  

For example, a variable called `subject` might have possible values of `history`, `mathematics`, `literature`. In this case, each subject might be **nominal**&mdash;given the same level of importance. However, you might have another variable called `class`, whose possible values are `freshman`, `sophomore`, `junior`, `senior`. In this case, the class variable is **ordinal**&mdash;its values have an ordered, hierarchical structure of importance. 

Machine learning models typically need all data to be numeric, and they generally use ordinal label encoding (method 1) and dummy encoding (method 3). 

In the next steps, you'll convert the following variables: `Continent`, `Country/Region`, and `Industry`, each using a different approach.

### Convert `Continent` to numeric

For the purposes of this exercise, suppose that the investment group has specified that they want to give more weight to continents with fewer unicorn companies because they believe this could indicate unrealized market potential.

**Question: Which type of variable would this make the `Continent` variable in terms of how it would be converted to a numeric data type?**

The Continent variable would be considered ordinal because the investment group wants to assign different weights to continents based on their potential market value. The categories would have an order of importance rather than being treated as equal categories.

Rank the continents in descending order from the greatest number of unicorn companies to the least.

In [17]:
# Rank the continents by number of unicorn companies

continent_count = companies['Continent'].value_counts()
continent_count

Continent
North America    586
Asia             310
Europe           143
South America     21
Oceania            8
Africa             3
Name: count, dtype: int64

Now, create a new column called `Continent Number` that represents the `Continent` column converted to numeric in the order of their number of unicorn companies, where North America is encoded as `1`, through Africa, encoded as `6`.

In [19]:
# Create numeric `Continent Number` column

continent_mapping = {
    "North America":1,
    "Asia":2,
    "Europe":3,
    "South America":4,
    "Oceania":5,
    "Africa":6
}

companies['Continent Number'] = companies["Continent"].replace(continent_mapping)
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn,High Valuation,Continent Number
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",5,high,2
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",10,high,1
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",10,high,2
3,Stripe,95,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",4,high,1
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",6,high,3

### Convert `Country/Region` to numeric

Now, suppose that within a given continent, each company's `Country/Region` is given equal importance. For analytical purposes, you want to convert the values in this column to numeric without creating a large number of dummy columns. Use label encoding of this nominal categorical variable to create a new column called `Country/Region Numeric`, wherein each unique `Country/Region` is assigned its own number.

In [24]:
# Create `Country/Region Numeric` column
# Create numeric categories for Country/Region

companies['Country/Region Numeric'] = companies['Country/Region'].astype('category').cat.codes
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn,High Valuation,Continent Number,Country/Region Numeric
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",5,high,2,9
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",10,high,1,44
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",10,high,2,9
3,Stripe,95,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",4,high,1,44
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",6,high,3,38

### Convert `Industry` to numeric

Finally, create dummy variables for the values in the `Industry` column.

In [26]:
# Convert `Industry` to numeric data
# Create dummy variables with Industry values

industry_dummies = pd.get_dummies(companies['Industry'])

# Combine `companies` DataFrame with new dummy Industry columns

companies = pd.concat([companies, industry_dummies], axis=1)

Display the first few rows of `companies`

In [27]:
companies.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Years to Unicorn,High Valuation,Continent Number,Country/Region Numeric,Artificial intelligence,Auto & transportation,Consumer & retail,Cybersecurity,Data management & analytics,E-commerce & direct-to-consumer,Edtech,Fintech,Hardware,Health,Internet software & services,Mobile & telecommunications,Other,"Supply chain, logistics, & delivery",Travel
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",5,high,2,9,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",10,high,1,44,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",10,high,2,9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
3,Stripe,95,2014-01-23,Fintech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",4,high,1,44,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",6,high,3,38,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False

**Question: Which categorical encoding approach did you use for each variable? Why?**

I used ordinal label encoding for the Continent variable because the categories were assigned an order based on the number of unicorn companies in each continent. I used nominal label encoding for Country/Region because countries do not have a natural order and each category was given equal importance. I used dummy encoding for Industry because industries are nominal categories without any hierarchy, and dummy variables allow each category to be represented without implying an order.

**Question: How does label encoding change the data?**

Label encoding changes categorical data into numerical values by assigning a unique integer to each category. This allows machine learning models to process categorical variables, but the assigned numbers do not always represent an actual order or importance unless the variable is ordinal.

**Question: What are the benefits of label encoding?**

The benefits of label encoding are that it converts categorical data into numerical values, allowing machine learning models to process the data. It is simple to implement, reduces the amount of memory needed compared to creating many dummy variables, and works well for ordinal variables or categorical variables with many unique values.

**Question: What are the disadvantages of label encoding?**

The disadvantages of label encoding are that it can create a false sense of order between categories when no real relationship exists. Machine learning models may incorrectly interpret higher numerical values as more important or greater than lower values. It is not ideal for nominal variables without a natural ranking.

## Conclusion

**What are some key takeaways that you learned during this lab?**

During this lab, I learned the importance of data cleaning, validation, and preparation before performing analysis. I learned how to identify and correct invalid values, handle duplicate data, and convert categorical variables into numerical formats using different encoding methods. I also learned that the choice of encoding method depends on the type of categorical variable and whether the categories have an order or hierarchy.

**Reference**

[Bhat, M.A. *Unicorn Companies*](https://www.kaggle.com/datasets/mysarahmadbhat/unicorn-companies)